"""add hotel settings

Revision ID: 5d0d7420d794
Revises: fb26a2eeb657
Create Date: 2026-04-26 18:43:40.255932

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5d0d7420d794'
down_revision: Union[str, None] = 'fb26a2eeb657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_name', sa.String(length=255), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('state_code', sa.String(length=5), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('checkin_time', sa.String(length=10), nullable=False),
    sa.Column('checkout_time', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=5), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_settings')
    # ### end Alembic commands ###
