"""add daily stats and night audit log

Revision ID: 7eafac8808ed
Revises: 5d0d7420d794
Create Date: 2026-04-28 05:47:56.878113

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7eafac8808ed'
down_revision: Union[str, None] = '5d0d7420d794'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('total_rooms', sa.Integer(), nullable=False),
    sa.Column('occupied_rooms', sa.Integer(), nullable=False),
    sa.Column('available_rooms', sa.Integer(), nullable=False),
    sa.Column('out_of_order_rooms', sa.Integer(), nullable=False),
    sa.Column('occupancy_pct', sa.Integer(), nullable=False),
    sa.Column('room_revenue', sa.Integer(), nullable=False),
    sa.Column('fb_revenue', sa.Integer(), nullable=False),
    sa.Column('other_revenue', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Integer(), nullable=False),
    sa.Column('total_discounts', sa.Integer(), nullable=False),
    sa.Column('new_bookings', sa.Integer(), nullable=False),
    sa.Column('checkins_count', sa.Integer(), nullable=False),
    sa.Column('checkouts_count', sa.Integer(), nullable=False),
    sa.Column('no_shows_count', sa.Integer(), nullable=False),
    sa.Column('adr', sa.Integer(), nullable=False),
    sa.Column('revpar', sa.Integer(), nullable=False),
    sa.Column('audit_ran_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audit_ran_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_stats_business_date'), 'daily_stats', ['business_date'], unique=True)
    op.create_table('night_audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bookings_processed', sa.Integer(), nullable=False),
    sa.Column('charges_posted', sa.Integer(), nullable=False),
    sa.Column('total_revenue_posted', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ran_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_night_audit_logs_business_date'), 'night_audit_logs', ['business_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_night_audit_logs_business_date'), table_name='night_audit_logs')
    op.drop_table('night_audit_logs')
    op.drop_index(op.f('ix_daily_stats_business_date'), table_name='daily_stats')
    op.drop_table('daily_stats')
    # ### end Alembic commands ###
