"""add_ota_push_logs

Revision ID: cb66d43794c2
Revises: e8d3aa75120f
Create Date: 2026-06-02 09:30:23.048402

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cb66d43794c2'
down_revision: Union[str, None] = 'e8d3aa75120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ota_push_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pushed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=True),
    sa.Column('push_type', sa.String(length=20), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('response_message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['ota_channel_configs.id'], ),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ota_push_logs_pushed_at'), 'ota_push_logs', ['pushed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ota_push_logs_pushed_at'), table_name='ota_push_logs')
    op.drop_table('ota_push_logs')
    # ### end Alembic commands ###
