"""add_invoice_label

Revision ID: e8d3aa75120f
Revises: bbfe189dbe2c
Create Date: 2026-06-02 09:16:35.041809

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e8d3aa75120f'
down_revision: Union[str, None] = 'bbfe189dbe2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('label', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'label')
    # ### end Alembic commands ###
